FROM kristoferb/spbase_ros2:humble

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qqy \
 && DEBIAN_FRONTEND=noninteractive apt-get install -qqy \
    ros-humble-desktop \
    python3-pip \
    nano \
 && rm -rf /var/lib/apt/lists/* \
 && pip3 install -U argcomplete \
 && echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc \
 && echo "set +e" >> ~/.bashrc 

