FROM kristoferb/spbase_ros2:galactic

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qqy \
 && DEBIAN_FRONTEND=noninteractive apt-get install -qqy \
    ros-galactic-desktop \
    python3-pip \
 && rm -rf /var/lib/apt/lists/* \
 && pip3 install -U argcomplete \
 && echo "/opt/ros/galactic/setup.bash" >> ~/.bashrc 

