FROM ros:foxy-ros-base-focal

# rust
RUN apt-get update -qqy \
 && apt-get install -qqy \
    llvm-dev \
    libclang-dev \
    clang \
    curl \
 && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
 && rm -rf /var/lib/apt/lists/* 
ENV PATH="/root/.cargo/bin:${PATH}"

COPY entrypoint.sh super_client.xml /
RUN chmod +x /entrypoint.sh / super_client.xml
ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]