FROM ros:foxy-ros-base-focal

# rust
RUN apt-get update -qqy \
 && apt-get install -qqy \
    llvm-dev \
    libclang-dev \
    clang \
 && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
 && rm -rf /var/lib/apt/lists/* 
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install cargo-chef --locked

COPY entrypoint.sh  /
RUN chmod +x /entrypoint.sh / 

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]