name: docker-core

on:
  workflow_dispatch:
# on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build_and_push_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./sp_core/
          file: ./sp_core/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spcore_ros2:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spcore_ros2:rolling

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./sp_core/
          file: ./sp_core/Dockerfile_humble
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spcore_ros2:humble

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./sp_core/
          file: ./sp_core/Dockerfile_galactic
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spcore_ros2:galactic
